### PR TITLE
Fix setup.py and test it with tox in Circle CI

### PR DESCRIPTION
**Pull request by nbren12**
Currently the setup.py file is missing some dependencies and refers to files not in `MANIFEST.in` which sometimes prevent this package from being `pip installed`.  This will make it hard to distribute this package via PyPi. These errors appeared because the code in`setup.py` is not actually being tested.

This PR adds the missing requirements (scipy and mpi4py) to the setup.py and tests it with [tox](https://tox.readthedocs.io/en/latest/). Tox is a widely used tool for testing python projects in isolated virtual environments and ensuring that the `setup.py` actually works. Another advantage is that it moves testing code out of the circle/config.yml and allows the local developer to trigger the tests identically to the CI.

~~The build time increased because tox now runs many thousands of more tests than before.~~

Other changes:
- removed caching logic from CircleCI. This caching logic would have to change for tox, and the environment install only takes about 1 minute, so it's probably not worth the complexity to optimize this portion of the build. This probably changed when `numcodecs` started uploading wheels.

Edit: I fixed this in 031eee4

### CODE REVIEW

**Review by mcgibbon — APPROVED** [review]

**Comment by nbren12** [comment]
This build fails on jenkins:
```
13:22:38 Processing /tmp/workspace/fv3gfs-util_PR/slave/gce-cpu/target/cpu
13:22:41 Requirement already satisfied: cftime>=1.2.1 in ./venv/lib/python3.6/site-packages (from fv3gfs-util==0.6.0) (1.2.1)
13:22:41 Requirement already satisfied: xarray>=0.15.1 in ./venv/lib/python3.6/site-packages (from fv3gfs-util==0.6.0) (0.15.1)
13:22:41 Requirement already satisfied: numpy>=0.15.0 in ./venv/lib/python3.6/site-packages (from fv3gfs-util==0.6.0) (1.16.5)
13:22:41 Requirement already satisfied: fsspec>=0.6.0 in ./venv/lib/python3.6/site-packages (from fv3gfs-util==0.6.0) (0.8.0)
13:22:41 Requirement already satisfied: zarr>=2.3.2 in ./venv/lib/python3.6/site-packages (from fv3gfs-util==0.6.0) (2.3.2)
13:22:41 Requirement already satisfied: typing_extensions>=3.7.4 in ./venv/lib/python3.6/site-packages (from fv3gfs-util==0.6.0) (3.7.4.3)
13:22:41 ERROR: Could not find a version that satisfies the requirement scipy>=1.6.0 (from fv3gfs-util)
13:22:41 ERROR: No matching distribution found for scipy>=1.6.0
```

**Comment by nbren12** [comment]
Now I am getting this error for the CUDA builds:
```
13:46:11 E   cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected
```

I don't see how changing the scipy version would cause this.

**Comment by nbren12** [comment]
launch jenkins

**Comment by ofuhrer** [comment]
@nbren12 Note that Jenkins is restarting because of an upgrade, so the test you launched might take a while.
@mcgibbon This build is giving an outrageous amount (20 MB) of stdout, any way of reducing failure output to something reasonable?

**Comment by nbren12** [comment]
Okay. Thanks for letting me know @ofuhrer. 

How are the jenkins machines administered btw? It might be less maintenance overhead if we moved them onto our k8s cluster. We could just `kubectl delete pod/jenkins-pod` if it's being flaky, and k8s would work it's magic...restarting the pod.  I'm not sure how hard this is.

**Comment by nbren12** [comment]
Anyway. I think the jenkins tests will pass this time.

**Comment by ofuhrer** [comment]
Thanks. I think @andrep tried this at one point and abandoned, but I don’t know the whole backstory.
The spinning up of GCP instances has been very stable. Provisioning the image for these instances is a bit of manual work, but we didn’t have to do it too often.
Not sure what the issue is here and why the CUDA device is not detected, especially if not related to the changes you are doing in this PR.

On Jan 28, 2021, at 2:30 PM, Noah D Brenowitz <notifications@github.com<mailto:notifications@github.com>> wrote:



Okay. Thanks for letting me know @ofuhrer<https://urldefense.com/v3/__https://github.com/ofuhrer__;!!CjdShnub!mxsfUqTMNJtHAuEBIvZabJYyMNI9McWZRPQO_12JJ_DXwgI917otU5G4XfG5ARg$>.

How are the jenkins machines administered btw? It might be less maintenance overhead if we moved them onto our k8s cluster. We could just kubectl delete pod/jenkins-pod if it's being flaky, and k8s would work it's magic...restarting the pod. I'm not sure how hard this is.

**Comment by mcgibbon** [comment]
> Anyway. I think the jenkins tests will pass this time.

Why did they pass?

**Pull request merged**
